version: '2'

services:
    nodeapp:
      build:
        context: ./app
      ports:
        - "3000:8080"
    nginx:
      restart: always
      build:
        context: ./nginx
      ports:
        - "80:80"